language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'cd(Pkg.dir("FinancialDerivatives")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("FinancialDerivatives")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

  # Documenter auto-deploy
  # following `using` instruction is for triggering precompilation
  #- julia -e 'Pkg.add("Documenter")'
  #- julia -e 'cd(Pkg.dir("FinancialDerivatives", "docs")); include("make.jl")'